# Generated by Django 4.1.7 on 2023-02-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(verbose_name='Дата заказа'),
        ),
    ]
